### ISSUE TITLE
xml dependency needs to be upgraded because it is conflicting with other aws related packages

### ISSUE THREAD

**Issue by oysterpack** [agilord/aws_client#224]
The **xml** package dependency version needs to be bumped because it is conflicting with other aws related packages to be upgraded:
```
Because aws_dynamodb_api >=0.1.1 depends on shared_aws_api ^0.2.1 which depends on xml ^4.2.0, aws_dynamodb_api >=0.1.1 requires xml ^4.2.0.
And because aws_client 0.2.0 depends on xml ^3.0.0 and no versions of aws_client match >0.2.0 <0.3.0, aws_dynamodb_api >=0.1.1 is incompatible with aws_client ^0.2.0.
So, because oysterpack depends on both aws_client ^0.2.0 and aws_dynamodb_api ^0.1.1, version solving failed.
```

My work around is to override the **xml** dependency:
```yaml
dependency_overrides:
  xml: 4.3.0
```

**Comment by Schwusch** [comment]
I wouldn't recommend using `aws_client` anymore if the reason you are using it is [SNS](https://pub.dev/packages/aws_sns_api) or [SQS](https://pub.dev/packages/aws_sqs_api). 

However if you are using the Lambda API, then yes, there is no alternative at the moment. If you want, I would appreciate a pull request with updated dependencies for `aws_client` in order to be compatible with the generated packages.

The goal is to generate a Lambda API from specifications in the future, so there will be no need to use `aws_client` at all.

**Comment by oysterpack** [comment]
Yes - I use the Lambda invoke API. I'll keep an eye out for dedicated Lambda API. 

If this package is deprecated, then it wouldn't be worth the time to update dependencies because the dependency_overrides is the work around ... the time would be better spent on working on the new Lambda API package :)
