### ISSUE TITLE
build_runner on +200 packages is very slow

### ISSUE THREAD

**Issue by xvrh** [agilord/aws_client#258]
Running `pub get` and `pub run build_runner build` on the +200 packages takes a lot of time (>30 minutes on my mac?).

Raw idea: 
- Generate all the API's in a single development package where each API has its own folder.
```
all_apis
  lib
    aws_accessanalyzer_api
      accessanalyzer-2019-11-01.dart
```

- Run `build_runner` on this `all_apis` package where it will generate the `.g.dart` files.
- Have an other command that copy the content of each folder and generate the corresponding package.

The `all_apis` package is not necessary versioned.

WDYT?

**Comment by Schwusch** [comment]
You should've seen how long it took before it was run in parallel :D
I say, if you have an idea, try it out. If it works, do a PR. 
It's _the_ biggest pain working with this repo at the moment, and all improvements are welcome.

My wish is that there is one command that runs on a fresh git clone and does everything, downloads definitions and generates all code, runs build_runner etc.
I don't think the generated code in the `all_apis` folder needs to be version controlled though, that would be unnecessary duplication.

I'd love to see how it affects code generation performance, since there is a huge amount of generated serialization. If it's quick, we might even be able to integrate it in CI/CD!

**Comment by xvrh** [comment]
I did a quick test with a `all_apis` package. `dart pub run build_runner build` takes less than a minute!
`Succeeded after 48.5s with 442 outputs (685 actions)`

I'll continue experimenting with this approach.
