### ISSUE TITLE
Chicken and Egg Question

### ISSUE THREAD

**Issue by biancashouse** [agilord/aws_client#266]
If I need to use my api key and secret in order to instantiate a Secrets Manager, what's the point of using it ?

**Comment by srinidhirao** [comment]
I am starting on this and have the same question. Any pointers as to where to start with? @Schwusch 

What do I need to get api key and secret, obviously, they are not meant to be hard-coded.

**Comment by Schwusch** [comment]
As a personal anecdote, you generally access Secrets Manager from the backend, which runs in AWS. That way, you have free access to Secrets Manager due to the IAM setting of the deploy user.

Alas, if you are running the server elsewhere, the access keys to access AWS services obviously cannot be stored in Secrets Manager.
You have to figure out how to store those access credentials in a secure way outside AWS.

Somewhat like accessing all passwords stored in a password manager, you generally need a master password in order to get the rest.

**Comment by Schwusch** [comment]
I can imagine a solution where a logged in user through Cognito, get access keys in order to call Secrets Manager. I haven't seen that kind of solution myself though.
