### ISSUE TITLE
[Test suite failures] Idempotency token

### ISSUE THREAD

**Issue by xvrh** [agilord/aws_client#283]
4 failures comes from "Input / Idempotency token auto fill" tests.

From what I understand, some members are marked with `idempotencyToken: true`. If not specified by the users, those members should be autofilled by the library with a generated uuid.

The test mocks the uuid generator to always use `00000000-0000-4000-8000-000000000000`

**Comment by Schwusch** [comment]
I'm having a look at this, and I'd like to bring in `package:uuid` for token generation.
There is no published null safe version yet because of the `package:crypto` dependency not having a null safe version yet.
A null safe release is [being prepared](https://github.com/Daegalus/dart-uuid/issues/50) though.
Any thoughts on bringing in this dependency?

**Comment by xvrh** [comment]
I don't have an opinion on this extra dependency.
If it's a problem we could also just do a small function ourself based on DateTime + Random.next().
