### ISSUE TITLE
aws_cognito_idp_api username validation fails

### ISSUE THREAD

**Issue by chirag729** [agilord/aws_client#313]
Username validation seems to be incorrect. I'm getting an error on adminDisableUser and adminDeleteUser with the username: 79fa9100-69d0-4fa0-aeef-68c6e7bf5d66

Invalid argument (username): Argument does not conform to [\p{L}\p{M}\p{S}\p{N}\p{P}]+: "79fa9100-69d0-4fa0-aeef-68c6e7bf5d66"

**Comment by Schwusch** [comment]
Hello @chirag729 and thanks for your bug report.
I checked with a number of services, such as https://regex101.com/, https://regexr.com/ and https://regexper.com/.
They all seem to conclude that this is not an JS/ECMA compatible regex, but a PCRE compatible one. 

I checked the [latest API definition](https://github.com/aws/aws-sdk-js/blob/master/apis/cognito-idp-2016-04-18.normal.json#L9923) in `aws-sdk-js`, and the [way `aws-sdk-js` validates patterns](https://github.com/aws/aws-sdk-js/blob/master/lib/param_validator.js#L171-L179).
It's puzzling, because this should fail in the JS SDK as well. We can't really fix this without fixing the API definition in [aws-sdk-js](https://github.com/aws/aws-sdk-js/) first. Best way would be to validate this error in that SDK as well and file a bug report.

Do you have any other ideas/input @xvrh @isoos ?

**Comment by isoos** [comment]
I think it is worth a try to check how the official JS API handles the issue, and see if it is applicable here.

**Comment by xvrh** [comment]
@Schwusch @isoos I've dug into that at some point.
The JS SDK doesn't enforce the regex actually.
This is a bit unfortunate but we should (must) do the same in Dart as those regex are Java regex and are sometime invalid.

**Comment by Schwusch** [comment]
@xvrh That is interesting. Do you know if it's individual regexes that are ignored, or all regexes in general?
If it's individual, do you know the mechanism of how to tell which one to ignore?

**Comment by xvrh** [comment]
All regexes are ignored (I think).
At the end, it's not really a big loss. The validation is just executed server-side instead of client-side.

**Comment by Schwusch** [comment]
[Looks](https://github.com/aws/aws-sdk-js/blob/master/ts/config.ts#L64) like you're [right](https://github.com/aws/aws-sdk-js/blob/master/lib/config.js#L555).
Fastest way forward would probably be to make a change in `shared_aws_api`, and make the `validateStringPattern()` function return immediately without doing any checks.
Later we can update the services to not call into that function at all.

**Comment by Schwusch** [comment]
`shared_aws_api` 1.0.1 is published with the #329 fix.
