### ISSUE TITLE
[not a issue- just a request] proper docs for the implementation

### ISSUE THREAD

**Issue by raenAtTrantor** [agilord/aws_client#314]
hey guys,
First of all, I would like to thank u guys for making aws more accessible to the flutter community.

this is a request for the developers to please provide the community with proper docs. For instance, I was trying to implement aws chime for video calling in my app could not figure out what to do. for now, I am settling for a native implementation.

if u guys can show me how to do this implementation I would love to document this for you.

thanks.

**Comment by arjunkn** [comment]
![image](https://user-images.githubusercontent.com/4979735/120437104-5f3c4800-c39d-11eb-89ec-420049af78dc.png)

Can anyone please tell me where is this documentation located?

**Comment by Schwusch** [comment]
On all pub packages there is an API reference, which in this case is documented automatically by the specification taken from the JS SDK. Unfortunately we cannot provide examples in more detail since the packages are generated.

Something that could be of more help is the [AWS code samples for the V2 JS SDK](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/sdk-code-samples.html) which have similar naming and paradigm.
![image](https://user-images.githubusercontent.com/8165610/120790222-f090f300-c532-11eb-939a-cf63a0ba7f2e.png)

**Comment by Schwusch** [comment]
Unless anyone has a suggestion on how to automatically generate code samples/better documentation I suggest we close this issue and reopen if there is more activity around this topic.
