### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by aigima** [agilord/aws_client#421]
This package depends on http ^0.13.1 and so it is incompatible with other plugins.

Furthermore, there are now other voices in aws polly that the plugin cannot handle.

**Comment by isoos** [comment]
The latest version of `package:aws_client` depends on `http: '>=0.13.1 <2.0.0'` which allows the latest `package:http` `1.2.1`. Not sure: what do you find incompatible?

**Comment by smcben** [comment]
e.g. Because aws_secretsmanager_api >=2.0.0 depends on shared_aws_api ^2.0.0 which depends on http ^0.13.1, aws_secretsmanager_api >=2.0.0 requires http ^0.13.1.

It's not obvious for people that they have to import (the whole kitchen sink) `aws_client` instead of `aws_secretsmanager_api` by itself

I fell into that trap myself 🕳️ 🏃‍♂️

**Comment by isoos** [comment]
Published `shared_aws_api`.
